### ISSUE TITLE
Sinkhorn motivation

### ISSUE THREAD

**Issue by vasudev13** [Zasder3/train-CLIP#25]
Hi, thanks for the awesome implementation!

I had a question with sinkhorn objective used in CustomWrapper. Is it motivated from [here](https://github.com/openai/CLIP/issues/25)? Would be great if you could mention bit more about it.

Cheers!

**Comment by Zasder3** [comment]
Funny enough it's actually from a students masters thesis titled: Data-Efficient Language-Supervised Zero-Shot Learning with Self-Distillation.

Hope this helps give some background!

**Comment by vasudev13** [comment]
I see, thanks for the direction.

Any chance if you could point me to the the official implementation of the thesis/paper? (if released publicly). I think the CVPR paper does not talk about Optimal Transport but the thesis does.

Thanks again for the clarification.

**Comment by Zasder3** [comment]
I was in contact with the author but they were not at liberty to provide their official code. I believe the CVPR version does in fact have some better pseudo-code though!
