### ISSUE TITLE
How to load a provided CLIP pre-trained model in your code?

### ISSUE THREAD

**Issue by zmykevin** [Zasder3/train-CLIP#26]
Hi Thanks for sharing, the code is neat and easy to follow. I have one question regarding fine-tuning a  pre-trained CLIP. 
I notice that in your train_finetune.py, instead of directly loaded a pre-trainend CLIP model you encode two separately defined image encoder and text encoder. I wonder if I want to fine-tune a specific pre-trained CLIP model such as "ViT/32B", how I can properly load the image encoder and text encoder? Thank you for your answer.

**Comment by Zasder3** [comment]
Funny enough I made a second version of the repo that does just that! Hope [this](https://github.com/Zasder3/train-CLIP-FT) helps :)

**Comment by zmykevin** [comment]
Wow man you are a star! Thank you so much.

**Comment by Zasder3** [comment]
Thank you for your kindness, I hope all works out well!
